import { Manrope, Space_Mono } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"

const bigger = localFont({
  src: "../public/fonts/BiggerDisplay.woff",
  display: "swap",
  variable: "--font-bigger",
  family: "Bigger Display, sans-serif",
})

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
})

const spaceMono = Space_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${bigger.variable} ${manrope.variable} ${spaceMono.variable}`}
    >
      <body className={manrope.className}>{children}</body>
    </html>
  )
}
